version: '3'

services:
  web:
    build: ./app
    command: gunicorn -c gconfig.py psd2bank.wsgi:application
    volumes:
      - static_volume:/usr/src/app/static
      - app_volume:/usr/src/app/
    ports:
      - 443:80
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

volumes:
  postgres_data:
  static_volume:
  app_volume:
